config/routes.rb
Rails.application.routes.draw do
  get 'home' => 'welcome#index'

  get 'about' => 'welcome#about'
  
  get 'contact' => 'welcome#contact'
  
  root 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @homeland = 'USA'
    @pictures = ['travel.jpg', 'atacama.jpg', 'atacama2.jpg', 'atacama3.jpg']
  end

  def about
    @color = params[:color]
    @size = params[:size]
  end
  
  def contact
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Travel</title>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" %>
  <link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a><%= link_to "Travel", root_path, class: 'navbar-brand'%></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path%></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="container">
<%= yield %>

</body>
</html>

app/views/welcome/about.html.erb
<h1>About Me</h1>
<p></p>
<p>My favorite color is <%= @color%></p>
<%= link_to "Blue", about_path(color:'blue'), class: "btn btn-primary" %>
<%= link_to "Red", about_path(color:'red'), class: "btn btn-danger" %>
<p>My shoes size is <%= @size %></p>
<% if @size.to_i > 12 %>
    <%= 'I have HUGE feet!'%>
<%end%> 

app/views/welcome/contact.html.erb
<h1>Contact Me</h1>
<p>Please reach out to me with any questions or comments!</p>
<p>Phone:(919)649-5192</p>
<p>Email:Ji.Edward@outlook.com</p>

app/views/welcome/index.html.erb
<h1>Welcome to my Travel Site!</h1>
<br/>

<h2>Places I've Visited Outside USA</h2>

<ul>
    <li><h3>Shanghai, China</h3> <br/>
    <%= image_tag 'travel.jpg', alt: 'Shanghai', id: 'pic', class: 'country', height: 300, width: 400, class: "img-responsive" %></li>
    <li><h3>Beijing, China</h3> <br/>
        <%= image_tag 'travel.jpg', alt: 'Beijing', id: 'pic', class: 'country', height: 300, width: 400, class: "img-responsive" %></li>
    <li><h3>Tianjing, China</h3> <br/>
    <%= image_tag 'travel.jpg', alt: 'Tianjing', id: 'pic', class: 'country', height: 300, width: 400, class: "img-responsive" %></li>
    <li><h3>Hong Kong</h3> <br/>
    <%= image_tag 'travel.jpg', alt: 'Hong Kong', id: 'pic', class: 'country', height: 300, width: 400, class: "img-responsive" %></li>
    <li><h3>Tokyo, Japan</h3> <br/>
    <%= image_tag 'travel.jpg', alt: 'Tokyo', id: 'pic', class: 'country', height: 300, width: 400, class: "img-responsive" %></li>
    <li><h3>Cozumel, Mexico</h3> <br/>
        <%= image_tag 'travel.jpg', alt: 'Cozumel', id: 'pic', class: 'country', height: 300, width: 400, class: "img-responsive" %></li>
        
</ul>